version: '3'

services: 
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports: 
      - '8080:8080'
    volumes: 
      - './api:/go/src/api'
    tty: true
    stdin_open: true