version: '3'

services: 
  api:
    build: .
    ports: 
      - '8080:8080'
    volumes: 
      - '.:/go/src'
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass