version: '3'

services: 
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports: 
      - '8080:8080'
    volumes: 
      - './api:/go/src/api'
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"